#!/bin/bash
set -eu pipefail

# RUNTIME_PACKAGES="make gcc g++ libc-dev libxml2-dev linux-headers postgresql-dev git"
RUNTIME_PACKAGES2="build-essential libpq-dev postgresql-client"
BUILD_PACKAGES="build-base curl-dev"

apt-get update -qq && \
apt-get upgrade && \
apt-get install -y --no-install-recommends "${RUNTIME_PACKAGES2}" && \
apt-get install --virtual build-packs "${BUILD_PACKAGES}" && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

# apk update && \
# apk upgrade && \
# apk add --no-cache \
# gcc \
# g++ \
# libc-dev \
# libxml2-dev \
# linux-headers \
# make \
# postgresql-dev \
# tzdata && \
# apk add --virtual build-packs --no-cache \
# build-base \
# curl-dev
