default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  # host: <%= ENV['POSTGRES_HOST'] %>
  # username: <%= ENV['POSTGRES_USER'] %>
  # password: <%= ENV['POSTGRES_PASS'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nercari_development

test:
  <<: *default
  database: nercari_test

production:
  <<: *default
  database: nercari_production